src/thirdparty/rendkit/svbrdf/models.py
import pickle

from scipy.misc import imread
from sqlalchemy import (Column, Integer, String, Float, LargeBinary,
                         ForeignKey)
from sqlalchemy.orm import relationship

from gravel.database import Base


class SVBRDF(Base):
    __tablename__ = 'svbrdfs'

    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)
    substance_name = Column(String(100), nullable=True)
    path = Column(String(1024))

    def to_jsd(self):
        return {
            'type': 'svbrdf',
            'path': self.path,
            'id': self.name,
            'name': self.name,
            'substance_name': self.substance_name,
        }

    @classmethod
    def from_jsd(cls, jsd):
        new = cls()
        new.id = jsd['id']
        new.path = jsd['path']
        new.substance_name = jsd['substance_name']
        new.name = jsd['name']
        return new

src/thirdparty/rendkit/svbrdf/views.py
import logging

from flask import Blueprint, abort, render_template
from scipy.misc import imread

from gravel.webutils import image_to_png_response, make_404, make_response
from svbrdf import models

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
blueprint = Blueprint('svbrdf', __name__,
                      template_folder='templates',
                      static_folder='static')


def get_rendering_or_abort(rendering_id):
    rendering = models.SVBRDFRendering.query.get(rendering_id)
    if rendering is None:
        abort(404)
    return rendering


@blueprint.route('/renderings/<rendering_id>/image.png', methods=['GET'])
def rendering_image(rendering_id):
    rendering = get_rendering_or_abort(rendering_id)
    return image_to_png_response(rendering.load_image())


@blueprint.route('/renderings/<rendering_id>/feature_patches.png', methods=['GET'])
def rendering_feature_patches(rendering_id):
    rendering = get_rendering_or_abort(rendering_id)
    feature_dao = models.SVBRDFRenderingFeature.query \
        .filter_by(rendering_id=rendering.id)\
        .first()
    return image_to_png_response(imread(feature_dao.patch_vis_path))

src/thirdparty/rendkit/svbrdf/templates/rendering_list.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('svbrdf.static', filename='css/svbrdf_list.css') }}" />
{% endblock %}


{% block contents %}
    <h1>{{ svbrdf.name }}</h1>
    <div id="rendering-list" class="list-table-container">
        <table id="rendering-table" class="list-table table table-striped">
        <tbody>
        <tr>
            <th>ID</th>
            <th>Image</th>
        </tr>
        {% for rendering in renderings %}
            <tr>
                <td>{{ rendering.id }}</td>
                <td>
                    <img class='blob'
                         src="{{ url_for('svbrdf.rendering_image',
                                         rendering_id=rendering.id) }}" />
                </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

src/thirdparty/rendkit/svbrdf/templates/svbrdf_list.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('svbrdf.static', filename='css/svbrdf_list.css') }}" />
{% endblock %}


{% block contents %}
    <div id="svbrdf-list" class="list-table-container">
    <table id="svbrdf-table" class="list-table table table-striped">
    <tbody>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Substance Name</th>
        <th></th>
    </tr>
    {% for svbrdf in svbrdfs %}
        <tr>
            <td>{{ svbrdf.id }}</td>
            <td>{{ svbrdf.name }}</td>
            <td>{{ svbrdf.substance_name }}</td>
            <td><a href="{{ url_for('svbrdf.list_svbrdf_renderings',
                                    svbrdf_id=svbrdf.id) }}">
                Renderings</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
{% endblock %}